module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'app.controller.ts',
    'auth/auth.controller.ts',
    'auth/auth.service.ts',
    'auth/strategies/jwt.strategy.ts',
    'auth/services/roles.service.ts',
    'auth/services/permissions.service.ts',
    'auth/utils/device-fingerprint.util.ts',
    'auth/utils/password.util.ts',
    'auth/utils/token.util.ts',
    'modules/users/users.controller.ts',
    'modules/users/uploads.controller.ts',
    'modules/users/users.service.ts',
    'modules/users/services/file-upload.service.ts',
    'modules/lost-pets/lost-pets.controller.ts',
    'modules/lost-pets/lost-pets.service.ts',
    'modules/pets/pets.controller.ts',
    'modules/pets/pets.service.ts',
    'modules/blockchain/stellar.service.ts',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
};