export enum Permission {
  // PetOwner
  READ_OWN_PETS = 'READ_OWN_PETS',
  UPDATE_OWN_PETS = 'UPDATE_OWN_PETS',
  CREATE_PETS = 'CREATE_PETS',
  SHARE_RECORDS = 'SHARE_RECORDS',

  // Medical Records
  READ_MEDICAL_RECORDS = 'READ_MEDICAL_RECORDS',
  CREATE_MEDICAL_RECORDS = 'CREATE_MEDICAL_RECORDS',
  UPDATE_MEDICAL_RECORDS = 'UPDATE_MEDICAL_RECORDS',
  DELETE_MEDICAL_RECORDS = 'DELETE_MEDICAL_RECORDS',

  // Veterinarian
  READ_ALL_PETS = 'READ_ALL_PETS',
  CREATE_TREATMENTS = 'CREATE_TREATMENTS',
  PRESCRIBE = 'PRESCRIBE',

  // VetStaff
  READ_ASSIGNED_PETS = 'READ_ASSIGNED_PETS',
  UPDATE_APPOINTMENTS = 'UPDATE_APPOINTMENTS',
  CREATE_NOTES = 'CREATE_NOTES',

  // Admin
  ALL_PERMISSIONS = 'ALL_PERMISSIONS',
}
