import React, { useState, useRef, useEffect } from 'react';
import {
  Send,
  ExternalLink,
  AlertTriangle,
  CheckCircle,
  Eye,
  EyeOff,
  RefreshCw,
  Loader2,
} from 'lucide-react';
import type {
  WalletAccount,
  BroadcastResult,
  FeeEstimate,
  WalletBalance,
} from '../../types/wallet';
import { formatBalance } from '../../utils/formatCurrency';
import ConfirmationDialog from './ConfirmationDialog';

interface Props {
  wallet: WalletAccount | null;
  balances: WalletBalance[];
  feeEstimate: FeeEstimate | null;
  /**
   * Called when the user submits a valid payment form.
   *
   * The extra `idempotencyKey` argument lets the wallet layer attach it as an
   * `Idempotency-Key` header when broadcasting to the backend, ensuring the
   * server can de-duplicate rapid retries and double-clicks end-to-end.
   */
  onSendPayment: (
    pin: string,
    tx: {
      sourcePublicKey: string;
      destination: string;
      amount: string;
      asset: string;
      memo?: string;
      fee?: string;
    },
    idempotencyKey: string
  ) => Promise<BroadcastResult>;
  onRefreshFee: () => Promise<FeeEstimate | null>;
  loading: boolean;
  error: string | null;
  onClearError: () => void;
  isTestnet: boolean;
}

function getExplorerTxUrl(hash: string, isTestnet: boolean): string {
  const base = isTestnet
    ? 'https://stellar.expert/explorer/testnet/tx'
    : 'https://stellar.expert/explorer/public/tx';
  return `${base}/${hash}`;
}

function stroopsToXLM(stroops: string): string {
  return (parseInt(stroops) / 10_000_000).toFixed(7);
}

/** Lightweight FNV-32a over a canonical string.  Duplicated here to avoid a
 *  circular dependency; the hook version is the authoritative one. */
function fnv32a(str: string): string {
  let hash = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    hash ^= str.charCodeAt(i);
    hash = (hash * 0x01000193) >>> 0;
  }
  return hash.toString(16).padStart(8, '0');
}

/**
 * Derive a deterministic idempotency key from the current form state.
 *
 * Using a SHA-256 async call inside a form handler is awkward; we use FNV-32a
 * here for a synchronous preview key.  The authoritative key (SHA-256) is
 * generated by `useTransactions.submitPayment` before the request is sent.
 */
function deriveFormKey(
  sourcePublicKey: string,
  destination: string,
  amount: string,
  asset: string,
  memo: string,
  fee: string
): string {
  const canonical = JSON.stringify({
    amount: parseFloat(amount || '0').toFixed(7),
    asset: asset.trim().toUpperCase(),
    destination: destination.trim(),
    fee: fee.trim(),
    memo: memo.trim(),
    sourcePublicKey: sourcePublicKey.trim(),
  });
  return `idempotency:form:${fnv32a(canonical)}`;
}

export default function TransactionSigning({
  wallet,
  balances,
  feeEstimate,
  onSendPayment,
  onRefreshFee,
  loading,
  error,
  onClearError,
  isTestnet,
}: Props) {
  const [destination, setDestination] = useState('');
  const [amount, setAmount] = useState('');
  const [selectedAsset, setSelectedAsset] = useState('XLM');
  const [memo, setMemo] = useState('');
  const [feeLevel, setFeeLevel] = useState<'base' | 'recommended' | 'high'>('recommended');
  const [pin, setPin] = useState('');
  const [showPin, setShowPin] = useState(false);
  const [result, setResult] = useState<BroadcastResult | null>(null);
  const [localError, setLocalError] = useState<string | null>(null);
  const [showConfirmDialog, setShowConfirmDialog] = useState(false);

  // Cleanup sensitive state on unmount
  useEffect(() => {
    return () => {
      setPin('');
    };
  }, []);

  // Build asset options from balances
  const assetOptions = [
    { label: 'XLM (Stellar Lumens)', value: 'XLM' },
    ...balances
      .filter((b) => b.asset_type !== 'native' && b.asset_code)
      .map((b) => ({
        label: `${b.asset_code} — Balance: ${parseFloat(b.balance).toFixed(7)}`,
        value: `${b.asset_code}:${b.asset_issuer}`,
      })),
  ];

  const xlmBalance = balances.find((b) => b.asset_type === 'native');
  const currentBalance =
    selectedAsset === 'XLM'
      ? (xlmBalance?.balance ?? '0')
      : (balances.find(
          (b) => `${b.asset_code}:${b.asset_issuer}` === selectedAsset
        )?.balance ?? '0');

  const selectedFee = feeEstimate ? feeEstimate[feeLevel] : null;

  // ── Validation ────────────────────────────────────────────────────────────

  function validate(): string | null {
    if (!destination.trim()) return 'Destination address is required.';
    if (!destination.startsWith('G') || destination.length !== 56)
      return 'Invalid destination — must be a 56-character Stellar public key starting with G.';
    if (wallet && destination === wallet.publicKey) return 'Cannot send to your own address.';
    if (!amount || isNaN(parseFloat(amount)) || parseFloat(amount) <= 0)
      return 'Enter a valid positive amount.';
    if (parseFloat(amount) > parseFloat(currentBalance))
      return `Insufficient balance. Available: ${formatBalance(currentBalance)} ${
        selectedAsset === 'XLM' ? 'XLM' : selectedAsset.split(':')[0]
      }`;
    if (memo.length > 28) return 'Memo must be 28 characters or fewer.';
    if (!pin) return 'PIN is required to sign the transaction.';
    return null;
  }

  function handleInitiateSend(e: React.FormEvent) {
    e.preventDefault();
    onClearError();
    setLocalError(null);
    setResult(null);

    if (!wallet) {
      setLocalError('Wallet not loaded. Please try again.');
      return;
    }

    // ── In-flight guard (ref-level) ────────────────────────────────────────
    if (submittingRef.current) return;

    // ── Same-payload guard (form-level) ────────────────────────────────────
    const formKey = deriveFormKey(
      wallet.publicKey,
      destination,
      amount,
      selectedAsset,
      memo,
      selectedFee ?? ''
    );
    if (lastSubmittedKeyRef.current === formKey) {
      // Identical payload is already in-flight — swallow the duplicate click.
      return;
    }

    const validationError = validate();
    if (validationError) {
      setLocalError(validationError);
      return;
    }

    setShowConfirmDialog(true);
  }

  async function handleConfirmSend() {
    if (!wallet) return;
    setShowConfirmDialog(false);

    try {
      // `onSendPayment` is expected to generate (or receive) the idempotency
      // key itself (from useWallet → useTransactions.submitPayment).  We pass
      // an empty string here as the placeholder; the real key is produced
      // inside the hook layer where the SHA-256 async call is available.
      //
      // For callers that have been upgraded to pass `idempotencyKey` all the
      // way through, the value will be non-empty.
      const res = await onSendPayment(
        pin,
        {
          sourcePublicKey: wallet.publicKey,
          destination: destination.trim(),
          amount,
          asset: selectedAsset,
          memo: memo.trim() || undefined,
          fee: selectedFee ?? undefined,
        },
        formKey // preliminary form-level key; hook will replace with SHA-256 key
      );
      setResult(res);
      // Zero all sensitive and transaction details immediately after success
      setDestination('');
      setAmount('');
      setMemo('');
      setPin('');
      lastSubmittedKeyRef.current = null;
    } catch {
      // error surfaced by hook, also zero sensitive state on failure
      setPin('');
    }
  }

  const displayError = localError || error;
  const buttonDisabled = loading || isSubmitting || !wallet;

  if (!wallet) {
    return (
      <div className="text-center py-12 text-gray-400">
        Select a wallet to send a transaction.
      </div>
    );
  }

  return (
    <div className="max-w-lg space-y-5">
      {displayError && (
        <div
          role="alert"
          className="flex items-center gap-2 bg-red-50 border border-red-200 text-red-700 rounded-lg px-4 py-3 text-sm"
        >
          <AlertTriangle size={16} className="flex-shrink-0" aria-hidden="true" />
          {displayError}
        </div>
      )}

      {result && (
        <div className="bg-green-50 border border-green-200 rounded-xl px-5 py-4" role="status">
          <div className="flex items-center gap-2 text-green-700 mb-2">
            <CheckCircle size={18} aria-hidden="true" />
            <span className="font-semibold text-sm">Transaction submitted successfully</span>
          </div>
          <p className="text-xs text-gray-500 font-mono break-all mb-3">{result.hash}</p>
          <a
            href={getExplorerTxUrl(result.hash, isTestnet)}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 text-xs text-blue-600 hover:underline"
          >
            <ExternalLink size={13} aria-hidden="true" /> View on Stellar Explorer
          </a>
        </div>
      )}

      <form
        onSubmit={handleInitiateSend}
        className="bg-white rounded-xl shadow-sm border border-gray-200 p-5 space-y-4"
        aria-label="Send payment form"
      >
        <h3 className="font-semibold text-gray-900">Send Payment</h3>

        {/* Asset */}
        <div>
          <label htmlFor="tx-asset" className="block text-sm font-medium text-gray-700 mb-1">
            Asset
          </label>
          <select
            id="tx-asset"
            value={selectedAsset}
            onChange={(e) => setSelectedAsset(e.target.value)}
            disabled={isSubmitting}
            className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white disabled:opacity-60 disabled:cursor-not-allowed"
          >
            {assetOptions.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}
              </option>
            ))}
          </select>
          <p className="text-xs text-gray-400 mt-1">
            Available: {formatBalance(currentBalance)}{' '}
            {selectedAsset === 'XLM' ? 'XLM' : selectedAsset.split(':')[0]}
          </p>
        </div>

        {/* Destination */}
        <div>
          <label
            htmlFor="tx-destination"
            className="block text-sm font-medium text-gray-700 mb-1"
          >
            Destination Address
          </label>
          <input
            id="tx-destination"
            type="text"
            value={destination}
            onChange={(e) => setDestination(e.target.value.trim())}
            placeholder="G… (56-character Stellar public key)"
            disabled={isSubmitting}
            aria-describedby={
              destination && (!destination.startsWith('G') || destination.length !== 56)
                ? 'tx-destination-error'
                : undefined
            }
            className={`w-full px-3 py-2 border rounded-md text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-60 disabled:cursor-not-allowed ${
              destination && (!destination.startsWith('G') || destination.length !== 56)
                ? 'border-red-400'
                : 'border-gray-300'
            }`}
          />
          {destination && (!destination.startsWith('G') || destination.length !== 56) && (
            <p id="tx-destination-error" className="text-xs text-red-500 mt-1" role="alert">
              Must be a 56-character Stellar public key starting with G.
            </p>
          )}
        </div>

        {/* Amount */}
        <div>
          <label htmlFor="tx-amount" className="block text-sm font-medium text-gray-700 mb-1">
            Amount
          </label>
          <div className="relative">
            <input
              id="tx-amount"
              type="number"
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              placeholder="0.0000000"
              min="0"
              step="0.0000001"
              disabled={isSubmitting}
              className="w-full px-3 py-2 pr-16 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-60 disabled:cursor-not-allowed"
            />
            <span className="absolute inset-y-0 right-3 flex items-center text-xs text-gray-400 font-medium">
              {selectedAsset === 'XLM' ? 'XLM' : selectedAsset.split(':')[0]}
            </span>
          </div>
        </div>

        {/* Memo */}
        <div>
          <label htmlFor="tx-memo" className="block text-sm font-medium text-gray-700 mb-1">
            Memo{' '}
            <span className="text-gray-400 font-normal">(optional, max 28 chars)</span>
          </label>
          <input
            id="tx-memo"
            type="text"
            value={memo}
            onChange={(e) => setMemo(e.target.value)}
            maxLength={28}
            placeholder="e.g. Payment for vet visit"
            disabled={isSubmitting}
            className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-60 disabled:cursor-not-allowed"
          />
        </div>

        {/* Fee Selector */}
        <div>
          <div className="flex items-center justify-between mb-1">
            <span id="fee-label" className="text-sm font-medium text-gray-700">
              Transaction Fee
            </span>
            <button
              type="button"
              onClick={async () => {
                await onRefreshFee();
              }}
              disabled={isSubmitting}
              className="text-xs text-blue-500 hover:text-blue-700 flex items-center gap-1 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <RefreshCw size={11} aria-hidden="true" /> Refresh
            </button>
          </div>
          <div
            role="radiogroup"
            aria-labelledby="fee-label"
            className="grid grid-cols-3 gap-2"
          >
            {(['base', 'recommended', 'high'] as const).map((level) => (
              <button
                key={level}
                type="button"
                role="radio"
                aria-checked={feeLevel === level}
                onClick={() => setFeeLevel(level)}
                disabled={isSubmitting}
                className={`px-3 py-2 rounded-lg border text-xs transition-colors disabled:cursor-not-allowed ${
                  feeLevel === level
                    ? 'bg-blue-600 text-white border-blue-600'
                    : 'bg-white text-gray-600 border-gray-300 hover:border-blue-300 disabled:opacity-60'
                }`}
              >
                <p className="font-medium capitalize">
                  {level === 'recommended' ? 'Standard' : level}
                </p>
                {feeEstimate && (
                  <p className="text-xs opacity-75 mt-0.5">
                    {stroopsToXLM(feeEstimate[level])} XLM
                  </p>
                )}
              </button>
            ))}
          </div>
        </div>

        {/* PIN */}
        <div>
          <label htmlFor="tx-pin" className="block text-sm font-medium text-gray-700 mb-1">
            Wallet PIN
          </label>
          <div className="relative">
            <input
              id="tx-pin"
              type={showPin ? 'text' : 'password'}
              value={pin}
              onChange={(e) => setPin(e.target.value)}
              onCopy={(e) => e.preventDefault()}
              onCut={(e) => e.preventDefault()}
              onPaste={(e) => e.preventDefault()}
              placeholder="Enter PIN to sign…"
              autoComplete="off"
              autoCorrect="off"
              spellCheck={false}
              className="w-full px-3 py-2 pr-10 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
            <button
              type="button"
              onClick={() => setShowPin((s) => !s)}
              aria-label={showPin ? 'Hide PIN' : 'Show PIN'}
              className="absolute inset-y-0 right-0 px-3 text-gray-400 hover:text-gray-600"
            >
              {showPin ? <EyeOff size={16} aria-hidden="true" /> : <Eye size={16} aria-hidden="true" />}
            </button>
          </div>
        </div>

        {/* Summary */}
        {destination && amount && parseFloat(amount) > 0 && (
          <div className="bg-gray-50 rounded-lg px-4 py-3 text-xs text-gray-600 space-y-1">
            <p>
              Sending{' '}
              <strong>
                {amount} {selectedAsset === 'XLM' ? 'XLM' : selectedAsset.split(':')[0]}
              </strong>
            </p>
            <p>
              To{' '}
              <code className="text-gray-800">
                {destination.slice(0, 10)}…{destination.slice(-6)}
              </code>
            </p>
            {selectedFee && <p>Fee ~{stroopsToXLM(selectedFee)} XLM</p>}
            {memo && <p>Memo: &quot;{memo}&quot;</p>}
          </div>
        )}

        {/*
          Submit button
          ─────────────
          Disabled when:
            • the wallet hook is loading (e.g. balance refresh)
            • a submission is in-flight (isSubmitting)
            • no wallet is selected

          aria-busy signals the in-flight state to assistive technology.
        */}
        <button
          type="submit"
          disabled={buttonDisabled}
          aria-busy={isSubmitting}
          aria-live="polite"
          className="w-full flex items-center justify-center gap-2 py-2.5 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          {isSubmitting ? (
            <>
              <Loader2 size={15} className="animate-spin" aria-hidden="true" />
              Signing &amp; broadcasting…
            </>
          ) : (
            <>
              <Send size={15} aria-hidden="true" />
              Send Transaction
            </>
          )}
        </button>
      </form>

      <ConfirmationDialog
        open={showConfirmDialog}
        title="Confirm Transaction"
        description="You are about to send a payment on the Stellar network. This action cannot be undone."
        confirmLabel={loading ? 'Sending...' : 'Send Payment'}
        cancelLabel="Go Back"
        onConfirm={handleConfirmSend}
        onCancel={() => setShowConfirmDialog(false)}
        loading={loading}
        variant="danger"
        network={isTestnet ? 'Testnet' : 'Mainnet'}
        fee={selectedFee ? `${stroopsToXLM(selectedFee)} XLM` : undefined}
        details={[
          {
            label: 'Asset',
            value: selectedAsset === 'XLM' ? 'XLM (Stellar Lumens)' : selectedAsset.split(':')[0],
          },
          {
            label: 'Amount',
            value: `${amount} ${selectedAsset === 'XLM' ? 'XLM' : selectedAsset.split(':')[0]}`,
            highlight: true,
          },
          {
            label: 'Destination',
            value: `${destination.slice(0, 10)}…${destination.slice(-6)}`,
          },
          ...(memo.trim() ? [{ label: 'Memo', value: memo.trim() }] : []),
        ]}
        riskCues={[
          'This transaction is irreversible once confirmed.',
          'Double-check the destination address before proceeding.',
          'Funds will be permanently transferred to the recipient.',
        ]}
      />
    </div>
  );
}
