import { PetSpecies } from '../entities/pet-species.enum';

export const BREEDS_DATA = [
  {
    name: 'Labrador Retriever',
    species: PetSpecies.DOG,
    description: 'Friendly, active and high-spirited companion.',
    lifeExpectancy: '10-12 years',
    sizeCategory: 'Large',
    careRequirements: 'High exercise needs, regular grooming.',
    commonHealthIssues: ['Hip dysplasia', 'Elbow dysplasia', 'Obesity'],
  },
  {
    name: 'German Shepherd',
    species: PetSpecies.DOG,
    description: 'Confident, courageous, and smart.',
    lifeExpectancy: '7-10 years',
    sizeCategory: 'Large',
    careRequirements: 'Regular mental and physical stimulation.',
    commonHealthIssues: ['Hip dysplasia', 'Degenerative myelopathy'],
  },
  {
    name: 'Golden Retriever',
    species: PetSpecies.DOG,
    description: 'Intelligent, friendly, and devoted.',
    lifeExpectancy: '10-12 years',
    sizeCategory: 'Large',
    careRequirements: 'Daily exercise, regular grooming.',
    commonHealthIssues: ['Cancer', 'Hip dysplasia'],
  },
  {
    name: 'Bulldog',
    species: PetSpecies.DOG,
    description: 'Calm, courageous, and friendly.',
    lifeExpectancy: '8-10 years',
    sizeCategory: 'Medium',
    careRequirements: 'Minimal exercise, skin fold cleaning.',
    commonHealthIssues: ['Respiratory issues', 'Skin infections'],
  },
  {
    name: 'Persian',
    species: PetSpecies.CAT,
    description: 'Quiet, sweet, and gentle.',
    lifeExpectancy: '10-15 years',
    sizeCategory: 'Medium',
    careRequirements: 'Daily grooming requires.',
    commonHealthIssues: ['Polycystic kidney disease', 'Breathing difficulties'],
  },
  {
    name: 'Maine Coon',
    species: PetSpecies.CAT,
    description: 'Gentle giant, friendly and playful.',
    lifeExpectancy: '12-15 years',
    sizeCategory: 'Large',
    careRequirements: 'Regular grooming.',
    commonHealthIssues: ['Hypertrophic cardiomyopathy', 'Hip dysplasia'],
  },
  {
    name: 'Parakeet',
    species: PetSpecies.BIRD,
    description: 'Friendly, affectionate, and easy to tame.',
    lifeExpectancy: '5-10 years',
    sizeCategory: 'Small',
    careRequirements: 'Social interaction, flying time.',
    commonHealthIssues: ['Tumors', 'Mites'],
  },
  {
    name: 'Holland Lop',
    species: PetSpecies.RABBIT,
    description: 'Energetic, friendly and compact.',
    lifeExpectancy: '7-10 years',
    sizeCategory: 'Small',
    careRequirements: 'Hay-based diet, exercise.',
    commonHealthIssues: ['Dental disease', 'GI stasis'],
  },
];
