import { SpeciesType, SizeCategory } from '../entities/breed.entity';

export const breedSeedData = [
  // Popular Dog Breeds
  {
    species: SpeciesType.DOG,
    name: 'Golden Retriever',
    size_category: SizeCategory.LARGE,
    temperament: ['Friendly', 'Intelligent', 'Devoted', 'Trustworthy'],
    common_health_issues: [
      'Hip Dysplasia',
      'Elbow Dysplasia',
      'Eye Conditions',
      'Heart Disease',
      'Cancer',
    ],
    life_expectancy: { min: 10, max: 12, average: 11 },
    care_requirements: {
      exercise_level: 'high',
      grooming_needs: 'moderate',
      training_difficulty: 'easy',
      good_with_kids: true,
      good_with_pets: true,
      apartment_friendly: false,
    },
    vaccination_schedule: {
      core_vaccines: ['Rabies', 'DHPP', 'Bordetella'],
      recommended_vaccines: ['Lyme Disease', 'Canine Influenza'],
      schedule_notes: 'Puppy series at 6, 9, 12 weeks, then annually',
    },
    description: 'A friendly, intelligent breed that is great with families and children.',
    origin_country: 'Scotland',
    physical_characteristics: {
      weight_range: { min: 55, max: 75, unit: 'lbs' },
      height_range: { min: 21, max: 24, unit: 'inches' },
      coat_type: 'Dense water-repellent double coat',
      colors: ['Golden', 'Light Golden', 'Dark Golden'],
    },
    breed_group: {
      akc_group: 'Sporting',
      purpose: ['Retriever', 'Gun Dog', 'Family Companion'],
    },
  },
  {
    species: SpeciesType.DOG,
    name: 'Labrador Retriever',
    size_category: SizeCategory.LARGE,
    temperament: ['Outgoing', 'Even-tempered', 'Active', 'Loyal'],
    common_health_issues: [
      'Hip Dysplasia',
      'Elbow Dysplasia',
      'Eye Conditions',
      'Exercise Induced Collapse',
    ],
    life_expectancy: { min: 10, max: 12, average: 11 },
    care_requirements: {
      exercise_level: 'high',
      grooming_needs: 'moderate',
      training_difficulty: 'easy',
      good_with_kids: true,
      good_with_pets: true,
      apartment_friendly: false,
    },
    vaccination_schedule: {
      core_vaccines: ['Rabies', 'DHPP', 'Bordetella'],
      recommended_vaccines: ['Lyme Disease', 'Canine Influenza'],
      schedule_notes: 'Puppy series at 6, 9, 12 weeks, then annually',
    },
    description: 'Americas most popular dog breed. Labs are friendly, outgoing, and active companions.',
    origin_country: 'Canada',
    physical_characteristics: {
      weight_range: { min: 55, max: 80, unit: 'lbs' },
      height_range: { min: 21, max: 24, unit: 'inches' },
      coat_type: 'Short, dense, water-repellent double coat',
      colors: ['Black', 'Yellow', 'Chocolate'],
    },
    breed_group: {
      akc_group: 'Sporting',
      purpose: ['Retriever', 'Gun Dog', 'Family Companion'],
    },
  },
  {
    species: SpeciesType.DOG,
    name: 'German Shepherd',
    size_category: SizeCategory.LARGE,
    temperament: ['Confident', 'Courageous', 'Smart', 'Versatile'],
    common_health_issues: [
      'Hip Dysplasia',
      'Elbow Dysplasia',
      'Bloat',
      'Degenerative Myelopathy',
    ],
    life_expectancy: { min: 9, max: 13, average: 11 },
    care_requirements: {
      exercise_level: 'high',
      grooming_needs: 'high',
      training_difficulty: 'moderate',
      good_with_kids: true,
      good_with_pets: true,
      apartment_friendly: false,
    },
    vaccination_schedule: {
      core_vaccines: ['Rabies', 'DHPP', 'Bordetella'],
      recommended_vaccines: ['Lyme Disease', 'Canine Influenza'],
      schedule_notes: 'Puppy series at 6, 9, 12 weeks, then annually',
    },
    description: 'Large, athletic dogs known for their loyalty, courage, and versatility.',
    origin_country: 'Germany',
    physical_characteristics: {
      weight_range: { min: 50, max: 90, unit: 'lbs' },
      height_range: { min: 22, max: 26, unit: 'inches' },
      coat_type: 'Double coat with dense outer coat',
      colors: ['Black and Tan', 'Sable', 'All Black'],
    },
    breed_group: {
      akc_group: 'Herding',
      purpose: ['Herding', 'Guard Dog', 'Police Work', 'Military'],
    },
  },

  // Small Dog Breeds
  {
    species: SpeciesType.DOG,
    name: 'French Bulldog',
    size_category: SizeCategory.SMALL,
    temperament: ['Adaptable', 'Playful', 'Smart', 'Easygoing'],
    common_health_issues: [
      'Brachycephalic Syndrome',
      'Hip Dysplasia',
      'Allergies',
      'Spinal Disorders',
    ],
    life_expectancy: { min: 10, max: 12, average: 11 },
    care_requirements: {
      exercise_level: 'low',
      grooming_needs: 'minimal',
      training_difficulty: 'moderate',
      good_with_kids: true,
      good_with_pets: true,
      apartment_friendly: true,
    },
    vaccination_schedule: {
      core_vaccines: ['Rabies', 'DHPP', 'Bordetella'],
      recommended_vaccines: ['Canine Influenza'],
      schedule_notes: 'Puppy series at 6, 9, 12 weeks, then annually',
    },
    description: 'Small, muscular dogs with characteristic bat ears and squashed face.',
    origin_country: 'France',
    physical_characteristics: {
      weight_range: { min: 20, max: 28, unit: 'lbs' },
      height_range: { min: 11, max: 13, unit: 'inches' },
      coat_type: 'Short, smooth coat',
      colors: ['Brindle', 'Fawn', 'White', 'Cream'],
    },
    breed_group: {
      akc_group: 'Non-Sporting',
      purpose: ['Companion', 'Family Pet'],
    },
  },

  // Popular Cat Breeds
  {
    species: SpeciesType.CAT,
    name: 'Persian',
    size_category: SizeCategory.MEDIUM,
    temperament: ['Quiet', 'Sweet', 'Calm', 'Affectionate'],
    common_health_issues: [
      'Polycystic Kidney Disease',
      'Hypertrophic Cardiomyopathy',
      'Breathing Problems',
      'Eye Issues',
    ],
    life_expectancy: { min: 12, max: 17, average: 14 },
    care_requirements: {
      exercise_level: 'low',
      grooming_needs: 'high',
      training_difficulty: 'easy',
      good_with_kids: true,
      good_with_pets: true,
      apartment_friendly: true,
    },
    vaccination_schedule: {
      core_vaccines: ['FVRCP', 'Rabies'],
      recommended_vaccines: ['FeLV', 'FIP'],
      schedule_notes: 'Kitten series at 6, 9, 12 weeks, then annually',
    },
    description: 'Known for their long, flowing coat and calm temperament.',
    origin_country: 'Iran',
    physical_characteristics: {
      weight_range: { min: 7, max: 12, unit: 'lbs' },
      height_range: { min: 8, max: 10, unit: 'inches' },
      coat_type: 'Long, flowing double coat',
      colors: ['White', 'Black', 'Blue', 'Red', 'Cream', 'Silver'],
    },
    breed_group: {
      cfa_group: 'Persian',
      purpose: ['Companion', 'Show Cat'],
    },
  },
  {
    species: SpeciesType.CAT,
    name: 'Maine Coon',
    size_category: SizeCategory.LARGE,
    temperament: ['Gentle', 'Friendly', 'Intelligent', 'Playful'],
    common_health_issues: [
      'Hypertrophic Cardiomyopathy',
      'Hip Dysplasia',
      'Spinal Muscular Atrophy',
      'Polycystic Kidney Disease',
    ],
    life_expectancy: { min: 13, max: 14, average: 13 },
    care_requirements: {
      exercise_level: 'moderate',
      grooming_needs: 'moderate',
      training_difficulty: 'easy',
      good_with_kids: true,
      good_with_pets: true,
      apartment_friendly: true,
    },
    vaccination_schedule: {
      core_vaccines: ['FVRCP', 'Rabies'],
      recommended_vaccines: ['FeLV'],
      schedule_notes: 'Kitten series at 6, 9, 12 weeks, then annually',
    },
    description: 'Large, rugged cats with tufted ears and bushy tails.',
    origin_country: 'United States',
    physical_characteristics: {
      weight_range: { min: 10, max: 25, unit: 'lbs' },
      height_range: { min: 10, max: 16, unit: 'inches' },
      coat_type: 'Heavy, shaggy coat',
      colors: ['Brown Tabby', 'Silver Tabby', 'Red', 'Black', 'White'],
    },
    breed_group: {
      cfa_group: 'Maine Coon',
      purpose: ['Companion', 'Mouser'],
    },
  },
  {
    species: SpeciesType.CAT,
    name: 'Siamese',
    size_category: SizeCategory.MEDIUM,
    temperament: ['Vocal', 'Social', 'Intelligent', 'Active'],
    common_health_issues: [
      'Respiratory Issues',
      'Dental Problems',
      'Heart Disease',
      'Eye Problems',
    ],
    life_expectancy: { min: 12, max: 20, average: 16 },
    care_requirements: {
      exercise_level: 'high',
      grooming_needs: 'minimal',
      training_difficulty: 'easy',
      good_with_kids: true,
      good_with_pets: true,
      apartment_friendly: true,
    },
    vaccination_schedule: {
      core_vaccines: ['FVRCP', 'Rabies'],
      recommended_vaccines: ['FeLV'],
      schedule_notes: 'Kitten series at 6, 9, 12 weeks, then annually',
    },
    description: 'Vocal, social cats with distinctive color points and blue eyes.',
    origin_country: 'Thailand',
    physical_characteristics: {
      weight_range: { min: 6, max: 14, unit: 'lbs' },
      height_range: { min: 8, max: 10, unit: 'inches' },
      coat_type: 'Short, fine coat',
      colors: ['Seal Point', 'Chocolate Point', 'Blue Point', 'Lilac Point'],
    },
    breed_group: {
      cfa_group: 'Siamese',
      purpose: ['Companion', 'Show Cat'],
    },
  },
];